name: test_rs_rat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-222.0.dev <3.0.0"

dependencies:
  dio: ^4.0.4
  http: ^0.13.4
  provider: ^6.0.5

  shared_preferences: ^2.0.13
  permission_handler: ^10.3.0
  toggle_switch: ^2.1.0
  #search_choices: ^2.2.0
  json_serializable: ^6.1.1
  json_annotation: any
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  google_fonts: ^2.2.0

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  retrofit_generator: any
  build_runner: ^2.1.5


flutter:

  uses-material-design: true
  assets:
    - assets/images/